version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: banana
      POSTGRES_USER: akin
      POSTGRES_DB: db


  api:
    container_name: api
    image: 'node:18'
    networks:
      - base_network
    ports:
      - '3000:3000'
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env

networks:
  base_network:

volumes:
  codei_db_data: